export function formatUser(user) {
  return {
    id: user._id.toString(),
    name: user.name,
    email: user.email,
    role: user.role,
    department: user.department || null,
    companyName: user.companyName || null,
    assignedDepartment: user.assignedDepartment || null,
    contractorRating: user.contractorRating || 5.0,
    trustScore: user.trustScore,
    verifiedReports: user.verifiedReports,
    totalReports: user.totalReports,
    createdAt: user.createdAt?.toISOString?.() ?? user.createdAt ?? null,
    roleHistory: user.roleHistory?.map((h) => ({
      previousRole: h.previousRole,
      newRole: h.newRole,
      changedBy: h.changedBy,
      changedByEmail: h.changedByEmail || null,
      reason: h.reason || null,
      timestamp: h.timestamp?.toISOString?.() ?? h.timestamp,
    })) || [],
    contractorApplication: user.contractorApplication ? {
      status: user.contractorApplication.status || 'none',
      requestedAt: user.contractorApplication.requestedAt?.toISOString?.() ?? user.contractorApplication.requestedAt ?? null,
      companyName: user.contractorApplication.companyName || null,
      assignedDepartment: user.contractorApplication.assignedDepartment || null,
      notes: user.contractorApplication.notes || null,
    } : null,
  }
}

export function formatIssue(issue) {
  return {
    id: issue._id.toString(),
    complaintId: issue.complaintId || `PT-2026-${issue._id.toString().slice(-5).toUpperCase()}`,
    title: issue.title,
    description: issue.description,
    category: issue.category,
    severity: issue.severity,
    status: issue.status,
    location: issue.location,
    area: issue.area || 'Unknown Area',
    imageUrl: issue.imageUrl,
    beforeGps: issue.beforeGps || (issue.location ? { lat: issue.location.lat, lng: issue.location.lng } : null),
    reporterId: issue.reporterId?.toString?.() ?? issue.reporterId,
    reporterName: issue.reporterName,
    reporterTrustScore: issue.reporterTrustScore,
    reportCount: issue.reportCount,
    clusterId: issue.clusterId,
    priorityScore: issue.priorityScore,
    validationResult: issue.validationResult,
    assignedTo: issue.assignedTo,
    contractorId: issue.contractorId?.toString?.() ?? issue.contractorId ?? null,
    contractorName: issue.contractorName || null,
    assignedAt: issue.assignedAt?.toISOString?.() ?? issue.assignedAt ?? null,
    assignedBy: issue.assignedBy || null,
    deadline: issue.deadline?.toISOString?.() ?? issue.deadline ?? null,
    slaStatus: issue.slaStatus || 'on_track',
    responsibleDepartment: issue.responsibleDepartment,
    afterImage: issue.afterImage || null,
    afterGps: issue.afterGps || null,
    afterSubmittedAt: issue.afterSubmittedAt?.toISOString?.() ?? issue.afterSubmittedAt ?? null,
    afterSubmittedBy: issue.afterSubmittedBy || null,
    verificationResult: issue.verificationResult || null,
    adminReviewedBy: issue.adminReviewedBy || null,
    adminReviewedAt: issue.adminReviewedAt?.toISOString?.() ?? issue.adminReviewedAt ?? null,
    adminReviewNotes: issue.adminReviewNotes || null,
    isRecurring: Boolean(issue.isRecurring),
    previousComplaintId: issue.previousComplaintId?.toString?.() ?? issue.previousComplaintId ?? null,
    previousComplaintCode: issue.previousComplaintCode || null,
    recurringDistanceMeters: issue.recurringDistanceMeters || null,
    previousRepairDate: issue.previousRepairDate?.toISOString?.() ?? issue.previousRepairDate ?? null,
    capturedAt: issue.capturedAt?.toISOString?.() ?? issue.capturedAt ?? null,
    syncedAt: issue.syncedAt?.toISOString?.() ?? issue.syncedAt ?? null,
    createdAt: issue.createdAt?.toISOString?.() ?? issue.createdAt,
    updatedAt: issue.updatedAt?.toISOString?.() ?? issue.updatedAt,
    votes: issue.votes,
    timeline: issue.timeline?.map(t => ({
      action: t.action,
      timestamp: t.timestamp?.toISOString?.() ?? t.timestamp,
      performedBy: t.performedBy,
      role: t.role,
      previousStatus: t.previousStatus,
      newStatus: t.newStatus,
      details: t.details,
    })) || [],
  }
}
